# Generated by Django 3.1.4 on 2020-12-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='details',
            field=models.TextField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='opinion',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='recommend',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='shoeModel',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
