# Generated by Django 3.1.4 on 2020-12-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='soldOut',
            field=models.BooleanField(choices=[(True, 'Available'), (False, 'Sold Out')], default=None),
            preserve_default=False,
        ),
    ]
