# Generated by Django 3.1.4 on 2020-12-19 10:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_auto_20201219_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='shoe_size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10'), ('10.5', '10.5'), ('11', '11')], default=None, max_length=40),
            preserve_default=False,
        ),
    ]
