# Generated by Django 3.1.4 on 2020-12-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_remove_shoe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
