# Generated by Django 3.1.4 on 2020-12-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_auto_20201206_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='soldOut',
            new_name='availability',
        ),
    ]
