# Generated by Django 3.1.4 on 2020-12-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_auto_20201206_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='availability',
            new_name='soldOut',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
