# Generated by Django 3.1.4 on 2020-12-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_shoe_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='releaseDate',
            field=models.CharField(blank=True, default=None, max_length=80),
            preserve_default=False,
        ),
    ]
