# Generated by Django 3.1.4 on 2020-12-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_auto_20201220_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='shoe_size',
            field=models.CharField(max_length=4),
        ),
    ]
