# Generated by Django 3.1.4 on 2020-12-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_auto_20201206_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='shoeAvail',
            field=models.CharField(choices=[('available', 'Available'), ('sold-out', 'Sold Out')], default=None, max_length=9),
            preserve_default=False,
        ),
    ]
