# Generated by Django 3.1.4 on 2020-12-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_shoe_shoeavail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='soldOut',
        ),
        migrations.AddField(
            model_name='shoe',
            name='shoeCategories',
            field=models.CharField(choices=[('New-Release', 'New Release'), ('Popular', 'Popular')], default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoeAvail',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold-out', 'Sold Out')], max_length=9),
        ),
    ]
