# Generated by Django 3.1.4 on 2020-12-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_auto_20201220_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewShoe',
        ),
    ]
