# Generated by Django 3.1.4 on 2020-12-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_delete_newshoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='shoe_size',
            field=models.CharField(max_length=50),
        ),
    ]
