# Generated by Django 3.1.4 on 2020-12-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_auto_20201207_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
