# Generated by Django 3.1.4 on 2020-12-21 03:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_auto_20201220_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image2',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
