# Generated by Django 3.1.4 on 2020-12-21 03:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0010_shoe_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', cloudinary.models.CloudinaryField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='image2',
        ),
    ]
