# Generated by Django 3.1.4 on 2020-12-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0011_auto_20201208_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='brand',
            new_name='shoeModel',
        ),
    ]
