# Generated by Django 3.1.4 on 2020-12-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0012_shoe_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='image2',
        ),
        migrations.AddField(
            model_name='shoe',
            name='image2',
            field=models.ManyToManyField(to='shoes.Image'),
        ),
    ]
