# Generated by Django 3.1.4 on 2020-12-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0013_auto_20201221_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='image2',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
