# Generated by Django 3.1.4 on 2020-12-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0014_upcomingshoe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpcomingShoe',
            new_name='NewShoe',
        ),
    ]
