# Generated by Django 3.1.4 on 2020-12-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0014_auto_20201221_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
