# Generated by Django 3.1.4 on 2020-12-09 14:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0015_auto_20201208_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10'), ('10.5', '10.5'), ('11', '11')], max_length=40),
        ),
    ]
