# Generated by Django 3.1.4 on 2020-12-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0015_auto_20201223_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.IntegerField(),
        ),
    ]
