# Generated by Django 3.1.4 on 2020-12-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0016_auto_20201209_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='newshoe',
            name='shoeBrand',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='shoeBrand',
        ),
        migrations.AddField(
            model_name='newshoe',
            name='brand_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoes.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='brand_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoes.brand'),
            preserve_default=False,
        ),
    ]
