# Generated by Django 3.1.4 on 2020-12-17 16:07

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0018_shoe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10'), ('10.5', '10.5'), ('11', '11')], max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.sizes'),
        ),
    ]
