# Generated by Django 3.1.4 on 2020-12-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0019_auto_20201217_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='size',
            new_name='sizes',
        ),
        migrations.RenameField(
            model_name='sizes',
            old_name='size',
            new_name='sizes',
        ),
    ]
