# Generated by Django 3.1.4 on 2020-12-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0021_auto_20201217_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoeModel', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='newshoe',
            name='shoeAvail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.availability'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='tags',
            field=models.ManyToManyField(to='shoes.Tags'),
        ),
    ]
