# Generated by Django 3.1.4 on 2020-12-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0022_auto_20201217_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='newshoe',
            name='sizes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoes.sizes'),
            preserve_default=False,
        ),
    ]
