# Generated by Django 3.1.4 on 2020-12-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0023_newshoe_sizes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
        migrations.RenameModel(
            old_name='Availability',
            new_name='Stock',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
